//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juegoPreguntas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public string nombreJugador { get; set; }
        public string puntuacion { get; set; }
        public Nullable<int> nivel { get; set; }
        public string resultado { get; set; }
        public int idPartida { get; set; }
    }
}
